#!/usr/bin/env python3
"""Simple CLI to inspect and manage saved/push_queue/ generated by server.py

Usage:
  push_queue.py list
  push_queue.py rm <jobfile>
  push_queue.py rm-all
"""

import argparse
import json
import os
import sys

# Attempt to locate saved/push_queue relative to repo layout
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# expected saved dir: ../0101/0101/src/public_html/saved/push_queue
SAVED_DIR = os.path.join(
    SCRIPT_DIR, "..", "0101", "0101", "src", "public_html", "saved"
)
QDIR = os.path.join(SAVED_DIR, "push_queue")


def list_jobs():
    if not os.path.isdir(QDIR):
        print("No push_queue directory found:", QDIR, file=sys.stderr)
        return 1
    jobs = []
    for name in sorted(os.listdir(QDIR)):
        path = os.path.join(QDIR, name)
        try:
            with open(path, "r", encoding="utf-8") as fh:
                j = json.load(fh)
        except Exception:
            j = None
        jobs.append((name, j))
    for name, j in jobs:
        if j is None:
            print(f"{name}: <invalid>")
        else:
            print(
                f"{name}: src={j.get('src')!s}, target={j.get('target')!s}, ts={j.get('ts')!s}, attempts={j.get('attempts', 0)}"
            )
    print(f"Total: {len(jobs)}")
    return 0


def rm_job(jobfile):
    if not os.path.isdir(QDIR):
        print("No push_queue directory found:", QDIR, file=sys.stderr)
        return 2
    jobpath = os.path.join(QDIR, jobfile)
    if not os.path.exists(jobpath):
        print(f"Job not found: {jobfile}", file=sys.stderr)
        return 3
    try:
        os.remove(jobpath)
        print(f"Removed {jobfile}")
        return 0
    except Exception as e:
        print(f"Error removing {jobfile}: {e}", file=sys.stderr)
        return 4


def rm_all():
    if not os.path.isdir(QDIR):
        print("No push_queue directory found:", QDIR, file=sys.stderr)
        return 2
    removed = 0
    for name in os.listdir(QDIR):
        try:
            os.remove(os.path.join(QDIR, name))
            removed += 1
        except Exception:
            pass
    print(f"Removed {removed} jobs")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(prog="push_queue.py")
    sub = parser.add_subparsers(dest="cmd")
    sub.add_parser("list")
    p_rm = sub.add_parser("rm")
    p_rm.add_argument("jobfile")
    sub.add_parser("rm-all")
    args = parser.parse_args(argv)
    if args.cmd == "list" or args.cmd is None:
        return list_jobs()
    if args.cmd == "rm":
        return rm_job(args.jobfile)
    if args.cmd == "rm-all":
        return rm_all()
    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
